version: "3"
services: 
  alpine:
    # name: alpine_env_
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./supervisor.conf:/source/supervisor.conf"
    command: /sbin/init
    networks:
      - alpine-network
  jaeger:
    image: jaegertracing/all-in-one:1.8
    ports:
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    networks:
      -  alpine-network
  postgresql:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=thanhdongnguyen
      - POSTGRES_USER=admin
      - POSTGRES_DB=sonar
    networks:
      -  alpine-network
  sonarqube:
    image: sonarqube 
    ports:
      - 9001:9000
      - 9093:9092
    environment:
      - SONARQUBE_JDBC_USERNAME=admin
      - SONARQUBE_JDBC_PASSWORD=thanhdongnguyen
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgresql/sonar
    networks:
      -  alpine-network
networks:
  alpine-network: