global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:

scrape_configs:
  - job_name: 'python'
    static_configs:
      - targets: ['localhost:8000']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9000']